FORMAT: 1A
HOST: https://server1.bohemiaenergy.cz/wsproxy/api/

# BEE WS Proxy

Web service proxy for BEE integration to ZIS.

## Sessions [/sessions]

User sessions.

### Create Session [POST]

Create a new session for an end-user.

+ Request

    + Attributes
        + userName: `josefnovak` (string, required) - User login name.
        + password: `Heslo01` (string, required) - User login password.

    + Body

            {
                "userName": "josefnovak",
                "password": "Heslo01"
            }

+ Response 201 (application/vnd.cz.bohemiaenergy.wsproxy.session.detail+json; version=1.0)

    + Attributes
        + token: `53551050-0000-48fc-bf25-354c345786dc` (string, required) - Session token, UUID.

    + Body

            {
                "token": "53551050-0000-48fc-bf25-354c345786dc"
            }


## Accounts [/accounts]

List of accounts.

### List Accounts [GET]

Find accounts.

+ Attributes
    + accountNumber: `12345678` (string) - Account number.
    + customerId: `1001` (number) - Customer id.

+ Response 200 (application/vnd.cz.bohemiaenergy.wsproxy.account.list+json; version=1.0)

    + Attributes
        + id: `2001` (number, required) - Id of the account.
        + accountNumber: `12345678` (string, required) - Account number.
        + url: `https://server1.bohemiaenergy.cz/wsproxy/api/accounts/2001` (string, required) - URL of account detail.

    + Body

            [
                {
                    "id": 2001,
                    "accountNumber": "12345678",
                    "url": "https://server1.bohemiaenergy.cz/wsproxy/api/accounts/2001"
                },
                {
                    "id": 2002,
                    "accountNumber": "87654321",
                    "url": "https://server1.bohemiaenergy.cz/wsproxy/api/accounts/2002"
                }
            ]


## Account Detail [/accounts/{accountId}]

Detail of an account.

+ Parameters
    + accountId: `2001` (number) - Id of the account.

### Get Account Detail [GET]

Retrieve the detail of an account by its id.

+ Response 200 (application/vnd.cz.bohemiaenergy.wsproxy.account.detail+json; version=1.0)

    + Attributes

        + id: `2001` (number, required) - Id of the account.
        + accountNumber: `12345678` (string, required) - Account number.
        + invoiceDeliveryType: letter, registeredLetter, email, databox (enum, required) - Type of invoice delivery.
        + invoiceMaturity: sent5, sent14, sent21, sent60, created10, created15, created20 (enum, required) - Invoice maturity.
        + overpaymentSettlementType: paymentOrder, postalOrder (enum, required) - Type of overpayment settlement.
        + currency: `CZK` (string, required) - Account currency.
        + status: active, inactive (enum, required) - Status of the account.
        + paymentMethods.type: deposit, invoice, creditNote (enum, required) - Type of payment.
        + paymentMethods.paymentMethod: paymentOrder, collectionOrder, SIPO, postalOrder (enum, required) - Method of payment.
        + paymentMethods.account: `20005550267/0100` (string) - The external account that originates or receives the payment.
        + customer.id: `1001` (number, required) - Customer id.
        + contracts.id: `5001` (number, required) - Contract id.
        + contracts.contractNumber: `6000432` (number, required) - Contract number.
        + transactions.supplyPoint.id: `30001` (number, required) - Supply point id.
        + transactions.documentType: `???` (enum, required) - Type of document.
        + transactions.documentVariableSymbol: `555666777` (string) - Variable symbol of the document.
        + transactions.paymentVariableSymbol: `777666555` (string) - Variable symbol of the payment.
        + transactions.invoicedAmount: `1234.56` (number) - Invoiced amount including VAT.
        + transactions.depositAmountBilled: `789.12` (number) - Deposit amount billed.
        + transactions.depositAmountUnbilled: `345.67` (number) - Deposit amount unbilled.
        + transactions.documentDate: `2015-12-31` (string) - Date of document.
        + transactions.debit: `234.56` (number) - Amount debited.
        + transactions.credit: `234.56` (number) - Amount credited.
        + transactions.dueDate: `2016-01-25` (string) - Date the payment is due.
        + transactions.paymentDate: `2016-01-24` (string) - Date the payment was made / received.
        + optouts.type: collection, accountAssignment, overpayment, reminder, smsReminder, interest, refund (enum, required) - Type of opt-out.
        + optouts.status: active, inactive (enum, required) - Status of the opt-out.

    + Body

            {
                "id": 2001,
                "accountNumber": "12345678",
                "invoiceDeliveryType": "letter",
                "invoiceMaturity": "sent14",
                "overpaymentSettlementType": "paymentOrder",
                "currency": "CZK",
                "status": "active",
                "paymentMethods": [
                    {
                        "type": "deposit",
                        "paymentMethod": "SIPO",
                        "account": "7666000444"
                    },
                    {
                        "type": "invoice",
                        "paymentMethod": "collectionOrder",
                        "account": "20005550267/0100"
                    },
                    {
                        "type": "creditNote",
                        "paymentMethod": "postalOrder"
                    }
                ],
                "customer": {
                    "id": 1001
                },
                "contracts": [
                    {
                        "id": 5001,
                        "contractNumber": "6000432"
                    },
                    {
                        "id": 5002,
                        "contractNumber": "6000433"
                    }
                ],
                "transactions": [
                    {
                        "supplyPoint": {
                            "id": 30001
                        },
                        "documentType": "???",
                        "documentVariableSymbol": "555666777",
                        "paymentVariableSymbol": "777666555",
                        "invoicedAmount": 1234.56,
                        "depositAmountBilled": 789.12,
                        "depositAmountUnbilled": 345.67,
                        "documentDate": "2015-12-31",
                        "debitAccount": 234.56,
                        "creditAccount": 0,
                        "dueDate": "2016-01-25",
                        "paymentDate": "2016-01-24"
                    },
                    {
                        "supplyPoint": {
                            "id": 30002
                        },
                        "documentType": "???",
                        "documentVariableSymbol": "555666778",
                        "paymentVariableSymbol": "777666556",
                        "invoicedAmount": 2345.67,
                        "depositAmountBilled": 890.12,
                        "depositAmountUnbilled": 456.78,
                        "documentDate": "2015-12-30",
                        "debitAccount": 0,
                        "creditAccount": 234.56,
                        "dueDate": "2016-01-27",
                        "paymentDate": "2016-01-26"
                    }
                ],
                "optouts": [
                    {
                        "type": "reminder",
                        "status": "active"
                    },
                    {
                        "type": "interest",
                        "status": "inactive"
                    },
                    {
                        "type": "overpayment",
                        "status": "active"
                    }
                ]
            }